-- AlterTable: Add missing pricing and configuration columns to Course table
ALTER TABLE "Course" ADD COLUMN "category" TEXT DEFAULT 'Général';
ALTER TABLE "Course" ADD COLUMN "registrationFee" DOUBLE PRECISION DEFAULT 45000;
ALTER TABLE "Course" ADD COLUMN "registrationFeeInterieur" DOUBLE PRECISION DEFAULT 35000;
ALTER TABLE "Course" ADD COLUMN "registrationFeeDiaspora" DOUBLE PRECISION DEFAULT 100000;
ALTER TABLE "Course" ADD COLUMN "monthlyFee" DOUBLE PRECISION DEFAULT 30000;
ALTER TABLE "Course" ADD COLUMN "monthlyFeeInterieur" DOUBLE PRECISION DEFAULT 25000;
ALTER TABLE "Course" ADD COLUMN "monthlyFeeOnline" DOUBLE PRECISION DEFAULT 25000;
ALTER TABLE "Course" ADD COLUMN "monthlyFeeBoth" DOUBLE PRECISION DEFAULT 35000;
ALTER TABLE "Course" ADD COLUMN "monthlyFeeDiaspora" DOUBLE PRECISION DEFAULT 35000;
ALTER TABLE "Course" ADD COLUMN "hasPresentiel" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Course" ADD COLUMN "hasOnline" BOOLEAN NOT NULL DEFAULT true;
